version: '3.9'

services:
  backend:
    build: .
    container_name: pm-backend
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/project_tool?schema=public
      - JWT_SECRET=supersecretkey
      - NODE_ENV=development
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate dev --name init && npm start"

  postgres:
    image: postgres:15
    container_name: pm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_tool
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
