services:
  backend:
    build: .
    container_name: pm-backend
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/project_tool?schema=public
      - JWT_SECRET=supersecretkey
      - NODE_ENV=development
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy && npm start"
    networks:
      - backend-network

  postgres:
    image: postgres:15
    container_name: pm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_tool
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d project_tool"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - backend-network

  prisma-studio:
    image: node:18-alpine
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/project_tool?schema=public
    command: >
      sh -c "npm install && npx prisma generate && npx prisma studio --port 5555 --browser none"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    profiles:
      - studio

  backend-tests:
    build: .
    container_name: pm-backend-tests
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/project_tool?schema=public
      - JWT_SECRET=supersecretkey
      - NODE_ENV=test
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - backend-network
    profiles:
      - tests


volumes:
  pgdata:

networks:
  backend-network:
